Warn if storage cannot be used
c4dt/omniledger pull request #279
Opened 2020-12-01 08:19 UTC by ineiti

If the browser is in private mode or refuses to use cookies, it doesn't
allow to store data. But this feature is needed by OmniLedger login.

This PR shows an explanation in that case and points to a c4dt.org
article with more information.

closes dedis/cothority#2415

2020-12-01 12:18 UTC, tharvik requested changes

2020-12-01 12:18 UTC, tharvik commented on webapp/src/app/byz-coin.service.ts
> +        "<br><br>System error message: " + e.toString());
It is not recommanded to generate HTML via typescript, as someone can insert random code here by manipulating the returned error. You should create a dedicated component which only accept an error which will be safely escaped by angular when interpolated.

2020-12-01 13:57 UTC, ineiti commented on webapp/src/app/byz-coin.service.ts
> +        "<br><br>System error message: " + e.toString());
Can't I simply escape the `e.toString()` with https://stackoverflow.com/questions/24816/escaping-html-strings-with-jquery ?

2020-12-01 14:15 UTC, tharvik commented on webapp/src/app/byz-coin.service.ts
> +        "<br><br>System error message: " + e.toString());
Maybe. Usually, writing yourself your own escaping library is very prone to bugs (as the mottos of "don't do your own crypto" or "don't trust your own parser"), and there is facilities already existing inside angular so why not use it direclty?

2020-12-02 11:44 UTC, ineiti commented on webapp/src/app/byz-coin.service.ts
> +        "<br><br>System error message: " + e.toString());
'cause I'm lazy? Anyway, I found a third one: `don't write your own testing harness`...

2020-12-02 16:14 UTC, ineiti commented on webapp/src/app/byz-coin.service.ts
> +        "<br><br>System error message: " + e.toString());
In fact the error lies even deeper: `showDialogInfo` accepts HTML code, so there must be many parts where the error might be used to inject HTML code... So I just added the `encodeURI` for the `e.toString()` here. OK?

2020-12-02 16:25 UTC, tharvik commented on webapp/src/app/byz-coin.service.ts
> +        "<br><br>System error message: " + e.toString());
That won't solve the security issue, only complexify a bit the payload needed to trigger it. The secure way is to create an independent component for each message.

If you really want to keep this pattern, look at https://angular.io/guide/security#direct-use-of-the-dom-apis-and-explicit-sanitization-calls on how to use angular's calls to make it secure.

2020-12-03 07:35 UTC, ineiti commented on webapp/src/app/byz-coin.service.ts
> +        "<br><br>System error message: " + e.toString());
Can you please create a commit to implement what you propose?

2020-12-03 17:08 UTC, tharvik commented on webapp/src/app/byz-coin.service.ts
> +        "<br><br>System error message: " + e.toString());
Here you go, I pushed it to this branch.
I found the root issue that allowed it to work. In `lib/dialog-okcancel.html`, it uses `innerHTML` which is a huge security risk as it allow trivial XSS. As only the `dbError` calls where using HTML formating, it removed it.

2020-12-04 12:49 UTC, ineiti commented on webapp/src/app/byz-coin.service.ts
> +        "<br><br>System error message: " + e.toString());
Cool - thanks a lot for taking care of this. I gotta admit I'm a bit disappointed by the slow user uptake, so I don't really care if we have a possible XSS attack from typescript-errors. Kudos to the one exploiting it ;)

But of course it's much nicer like that! Great!

2020-12-04 13:02 UTC, tharvik approved these changes

2020-12-04 14:02 UTC, merged